### ISSUE TITLE
Update front end with back end changes

### ISSUE THREAD

**Issue by Naamloos** [Naamloos/CHANdler#3]
check:
https://github.com/NaamloosDT/CHANdler/pull/2

**Comment by li223** [comment]
Api Changes
`/api/thread/post?thread=[thread]` is now `/api/thread/posts?id=[id]`

Added `/api/thread/single?id=[id]`

`/api/thread/create` now returns the created thread

Commentted out all of ValuesController as it creates dead endpoints

Added `/api/webhooks/subscribe?url=[url]&password=[password]&boardtag=[boardtag]&threadid=[threadid]`

Added `/api/webhooks/unsubscribe?password=[password]&id=[id]`

**Comment by li223** [comment]
Closing now as the changes are synced and everything works. Mostly.
